### ISSUE TITLE
CKAN-Oskari cron job database connection error

### ISSUE THREAD

**Issue by senoadiw** [geoenvo/oskari-server-extension-dps#2]
The cron job gives an error on not being able to connect/authenticate to the database CKAN and Oskari database.

Screenshot
![error jetty ckan-oskari sync](https://user-images.githubusercontent.com/1198399/85509128-a4012000-b61f-11ea-942f-d30cf6f10041.png)

Jetty log
[2020_06_24.jetty.log](https://github.com/geoenvo/oskari-server-extension-dps/files/4823599/2020_06_24.jetty.log)

**Comment by mr-lev1** [comment]
There was an error in my code, the property names were incorrect (copy-paste error :D).

I pushed some fixes, should work now!
